/*
Deployment script for Geco.Old

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Geco"
:setvar DefaultFilePrefix "Geco"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[Contents]...';


GO
ALTER TABLE [dbo].[Contents]
    ADD [AlbumId] UNIQUEIDENTIFIER NULL,
        [VideoId] UNIQUEIDENTIFIER NULL,
        [MapUrl]  NVARCHAR (100)   NULL;


GO
PRINT N'Creating [dbo].[Contents].[IX_FK_AlbumContent]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_AlbumContent]
    ON [dbo].[Contents]([AlbumId] ASC);


GO
PRINT N'Creating [dbo].[Contents].[IX_FK_VideoContent]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_VideoContent]
    ON [dbo].[Contents]([VideoId] ASC);


GO
PRINT N'Creating [dbo].[Albums]...';


GO
CREATE TABLE [dbo].[Albums] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Name]                NVARCHAR (100)   NOT NULL,
    [AuthInfo_CreatedBy]  NVARCHAR (50)    NOT NULL,
    [AuthInfo_Created]    DATETIME         NOT NULL,
    [AuthInfo_ModifiedBy] NVARCHAR (50)    NOT NULL,
    [AuthInfo_Modified]   DATETIME         NOT NULL,
    CONSTRAINT [PK_Albums] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Contents_Event]...';


GO
CREATE TABLE [dbo].[Contents_Event] (
    [StartingDate] DATETIME         NOT NULL,
    [EndingDate]   DATETIME         NOT NULL,
    [ContentId]    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Contents_Event] PRIMARY KEY CLUSTERED ([ContentId] ASC)
);


GO
PRINT N'Creating [dbo].[Contents_News]...';


GO
CREATE TABLE [dbo].[Contents_News] (
    [Date]      DATETIME         NOT NULL,
    [ContentId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Contents_News] PRIMARY KEY CLUSTERED ([ContentId] ASC)
);


GO
PRINT N'Creating [dbo].[DocumentContent]...';


GO
CREATE TABLE [dbo].[DocumentContent] (
    [Document_Id]       UNIQUEIDENTIFIER NOT NULL,
    [Content_ContentId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_DocumentContent] PRIMARY KEY CLUSTERED ([Document_Id] ASC, [Content_ContentId] ASC)
);


GO
PRINT N'Creating [dbo].[DocumentContent].[IX_FK_DocumentContent_Content]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_DocumentContent_Content]
    ON [dbo].[DocumentContent]([Content_ContentId] ASC);


GO
PRINT N'Creating [dbo].[Documents]...';


GO
CREATE TABLE [dbo].[Documents] (
    [Id]   UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR (100)   NOT NULL,
    [Path] NVARCHAR (300)   NULL,
    [Link] NVARCHAR (250)   NULL,
    CONSTRAINT [PK_Documents] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Photos]...';


GO
CREATE TABLE [dbo].[Photos] (
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    [Name]        NVARCHAR (100)   NOT NULL,
    [Path]        NVARCHAR (300)   NOT NULL,
    [Description] NVARCHAR (300)   NOT NULL,
    [AlbumId]     UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_Photos] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Photos].[IX_FK_AlbumPhoto]...';


GO
CREATE NONCLUSTERED INDEX [IX_FK_AlbumPhoto]
    ON [dbo].[Photos]([AlbumId] ASC);


GO
PRINT N'Creating [dbo].[VideoSet]...';


GO
CREATE TABLE [dbo].[VideoSet] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [Url]          NVARCHAR (150)   NULL,
    [EmbeddedCode] NVARCHAR (500)   NULL,
    CONSTRAINT [PK_VideoSet] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FK_Event_inherits_Content]...';


GO
ALTER TABLE [dbo].[Contents_Event] WITH NOCHECK
    ADD CONSTRAINT [FK_Event_inherits_Content] FOREIGN KEY ([ContentId]) REFERENCES [dbo].[Contents] ([ContentId]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_News_inherits_Content]...';


GO
ALTER TABLE [dbo].[Contents_News] WITH NOCHECK
    ADD CONSTRAINT [FK_News_inherits_Content] FOREIGN KEY ([ContentId]) REFERENCES [dbo].[Contents] ([ContentId]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK_DocumentContent_Document]...';


GO
ALTER TABLE [dbo].[DocumentContent] WITH NOCHECK
    ADD CONSTRAINT [FK_DocumentContent_Document] FOREIGN KEY ([Document_Id]) REFERENCES [dbo].[Documents] ([Id]);


GO
PRINT N'Creating [dbo].[FK_DocumentContent_Content]...';


GO
ALTER TABLE [dbo].[DocumentContent] WITH NOCHECK
    ADD CONSTRAINT [FK_DocumentContent_Content] FOREIGN KEY ([Content_ContentId]) REFERENCES [dbo].[Contents] ([ContentId]);


GO
PRINT N'Creating [dbo].[FK_AlbumPhoto]...';


GO
ALTER TABLE [dbo].[Photos] WITH NOCHECK
    ADD CONSTRAINT [FK_AlbumPhoto] FOREIGN KEY ([AlbumId]) REFERENCES [dbo].[Albums] ([Id]);


GO
PRINT N'Creating [dbo].[FK_AlbumContent]...';


GO
ALTER TABLE [dbo].[Contents] WITH NOCHECK
    ADD CONSTRAINT [FK_AlbumContent] FOREIGN KEY ([AlbumId]) REFERENCES [dbo].[Albums] ([Id]);


GO
PRINT N'Creating [dbo].[FK_VideoContent]...';


GO
ALTER TABLE [dbo].[Contents] WITH NOCHECK
    ADD CONSTRAINT [FK_VideoContent] FOREIGN KEY ([VideoId]) REFERENCES [dbo].[VideoSet] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Contents_Event] WITH CHECK CHECK CONSTRAINT [FK_Event_inherits_Content];

ALTER TABLE [dbo].[Contents_News] WITH CHECK CHECK CONSTRAINT [FK_News_inherits_Content];

ALTER TABLE [dbo].[DocumentContent] WITH CHECK CHECK CONSTRAINT [FK_DocumentContent_Document];

ALTER TABLE [dbo].[DocumentContent] WITH CHECK CHECK CONSTRAINT [FK_DocumentContent_Content];

ALTER TABLE [dbo].[Photos] WITH CHECK CHECK CONSTRAINT [FK_AlbumPhoto];

ALTER TABLE [dbo].[Contents] WITH CHECK CHECK CONSTRAINT [FK_AlbumContent];

ALTER TABLE [dbo].[Contents] WITH CHECK CHECK CONSTRAINT [FK_VideoContent];


GO
PRINT N'Update complete.';


GO
