//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GECO.Model.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using GECO.DomainClasses;
    
    public partial class GecoModelContainer : DbContext, IDbContext
    {
        public GecoModelContainer()
            : base("name=GecoModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    	public new IDbSet<T> Set<T>() where T : class
        {
          return base.Set<T>();
        }
    
        public override int SaveChanges()
        {
          this.ApplyStateChanges();
          return base.SaveChanges();
        }
    
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<Video> VideoSet { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    }
}
