//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GECO.DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video : Entity
    {
        public Video()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public string EmbeddedCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
    }
}
